import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rober_000' at '9/24/17 7:38 PM' with Gradle 2.13
 *
 * @author rober_000, @date 9/24/17 7:38 PM
 */
public class APIConnectionTest {
	
	@Test
	public void connectionIsWorking (){
		   
	         given().when().get("URL").then().statusCode(200);
	     }
            
        }
	
	
        
