import java.util.Date;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rober_000' at '9/24/17 7:38 PM' with Gradle 2.13
 *
 * @author rober_000, @date 9/24/17 7:38 PM
 */


public class APIconnection {
	
	
	

	
}